---

# Configuring IPSec on Router on siteB
- hosts: siteb
  gather_facts: false
  connection: local

  vars:
    cli:
      username: ec2-user
      ssh_keyfile: key1.pem
  # vars:
  #   cli:
  #     username: cisco
  #     password: cisco
  tasks:
    - name: add Basic Config
      ios_config:
        provider: "{{cli}}"
        lines:
          - hostname siteB
          - no ip domain lookup

    - name: add ospf on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - router-id 10.0.2.11
          - neighbor 10.0.110.1
        parents:
          - router ospf 1

    - name: add vrf definition site1 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - rd 1111:2
        parents:
          - vrf definition site1

    - name: add vrf definition site2 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - rd 2222:2
        parents:
          - vrf definition site2

    - name: add vrf definition site1 on siteA      
      ios_config:
        provider: "{{cli}}"
        lines:
          - route-target import 2:2
          - route-target export 2:2
          - route-target export 111:1000000
          - route-target import 111:1000000
          - route-target export 111:1000000 stitching
          - route-target import 111:1000000 stitching
        parents:
          - vrf definition site1
          - address-family ipv4

    - name: add vrf definition site2 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - route-target import 2:2
          - route-target export 2:2
          - route-target export 222:1000000
          - route-target import 222:1000000
          - route-target export 222:1000000 stitching
          - route-target import 222:1000000 stitching
        parents:
          - vrf definition site2
          - address-family ipv4

    - name: add bridge-domain1 on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - member vni 1000000
        parents:
          - bridge-domain 1

    - name: add bridge-domain2 on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - member vni 2000000
        parents:
          - bridge-domain 2

    # - name: configuring GigabitEthernet1 interface on siteB
    #   ios_config:
    #     provider: "{{cli}}"
    #     lines:
    #       # - no shutdown #ip address 10.0.2.11 255.255.255.0
    #       - mtu 9216
    #     parents:
    #       - interface GigabitEthernet1
          
    - name: configuring GigabitEthernet2 interface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site2
          - ip address 10.0.22.10 255.255.255.0
        parents:
          - interface GigabitEthernet2

    - name: configuring GigabitEthernet3 interface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site1
          - ip address 10.0.21.10 255.255.255.0
        parents:
          - interface GigabitEthernet3

    - name: add loopback1 interface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - description VTEP1
          - ip address 10.0.20.21 255.255.255.255
          - ip ospf 1 area 0
        parents:
          - interface loopback1

    - name: add loopback2 interface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - description VTEP2
          - ip address 10.0.20.22 255.255.255.255
          - ip ospf 1 area 0
        parents:
          - interface loopback2

    - name: add Tunnel100 for interconnection with siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - ip address 10.0.110.2 255.255.255.252
          - tunnel source 10.0.2.11
          - tunnel destination 10.0.2.10
          - tunnel mode ipip
          - ip ospf network non-broadcast
          - ip ospf 1 area 0
        parents:
          - interface Tunnel100

    - name: add BDI1 subinterface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - description L3VNI-SVI
          - vrf forwarding site1
          - ip address 10.0.33.1 255.255.255.0
        parents:
          - interface BDI1

    - name: add BDI1 subinterface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - description L3VNI-SVI
          - vrf forwarding site2
          - ip address 10.0.33.2 255.255.255.0
        parents:
          - interface BDI2

    - name: add nve1 subinterface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - no ip address
          - source-interface Loopback1
          - host-reachability protocol bgp
          - member vni 1000000 vrf site1
        parents:
          - interface nve1

    - name: add nve2 subinterface on siteB
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - no ip address
          - source-interface Loopback2
          - host-reachability protocol bgp
          - member vni 2000000 vrf site2
        parents:
          - interface nve2

    - name: add BGP on Central Router for neighborship
      ios_config:
        provider: "{{cli}}"
        lines:
          - neighbor 10.0.2.10 remote-as 65000
        parents:
          - router bgp 65000

    - name: add BGP on Central Router for address-family ipv4
      ios_config:
        provider: "{{cli}}"
        lines:
          - no neighbor 10.0.2.10 activate
          - default-information originate
          - exit-address-family
        parents:
          - router bgp 65000
          - address-family ipv4

    - name: add BGP on Central Router for address-family l2vpn evpn
      ios_config:
        provider: "{{cli}}"
        lines:
          - rewrite-evpn-rt-asn
          - neighbor 10.0.2.10 activate
          - neighbor 10.0.2.10 send-community both
          - exit-address-family
        parents:
          - router bgp 65000
          - address-family l2vpn evpn

    - name: add BGP on Central Router for address-family ipv4 vrf site1 
      ios_config:
        provider: "{{cli}}"
        lines:
          - advertise l2vpn evpn
          - redistribute connected
          - exit-address-family
        parents:
          - router bgp 65000
          - address-family ipv4 vrf site1 

    - name: add BGP on Central Router for address-family ipv4 vrf site2
      ios_config:
        provider: "{{cli}}"
        lines:
          - advertise l2vpn evpn
          - redistribute connected
          - exit-address-family
        parents:
          - router bgp 65000
          - address-family ipv4 vrf site2