---

# Configuring IPSec on Router on siteA
- hosts: sitea
  gather_facts: false
  connection: local

  vars:
    cli:
      username: ec2-user
      # ssh_keyfile: key1.pem
  # vars:
  #   cli:
  #     username: cisco
  #     password: cisco
  tasks:
    - name: add Basic Config
      ios_config:
        provider: "{{cli}}"
        lines:
          - hostname siteA
          - no ip domain lookup

    - name: add vrf definition site1 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - rd 1111:1
        parents:
          - vrf definition site1

    - name: add vrf definition site2 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - rd 2222:1
        parents:
          - vrf definition site2

    - name: add vrf definition site1 on siteA      
      ios_config:
        provider: "{{cli}}"
        lines:
          - route-target export 111:1000000
          - route-target export 1:1
          - route-target import 111:1000000
          - route-target import 1:1
          - route-target export 111:1000000 stitching
          - route-target import 111:1000000 stitching
        parents:
          - vrf definition site1
          - address-family ipv4

    - name: add vrf definition site2 on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - route-target export 222:1000000
          - route-target export 1:1
          - route-target import 222:1000000
          - route-target import 1:1
          - route-target export 222:1000000 stitching
          - route-target import 222:1000000 stitching
        parents:
          - vrf definition site2
          - address-family ipv4
      
    - name: add ospf on siteA for inter-vrf routing for vrf site1
      ios_config:
        provider: "{{cli}}"
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
        parents:
          - router ospf 10 vrf site1

    - name: add ospf on siteA for inter-vrf routing for vrf site2
      ios_config:
        provider: "{{cli}}"
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
        parents:
          - router ospf 20 vrf site2

    # - name: add GigabitEthernet1 interface on siteA
    #   ios_config:
    #     provider: "{{cli}}"
    #     lines:
    #       - no shutdown
    #       - ip address 10.0.1.11 255.255.255.0
    #     parents:
    #       - interface GigabitEthernet1

    - name: add Tunnel10 for ipip over ipsec on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site1
          - ip address 10.0.101.2 255.255.255.252
          - tunnel source 10.0.1.11
          - tunnel destination 10.0.105.1
        parents:
          - interface Tunnel10

    - name: add Tunnel20 for ipip over ipsec on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site2
          - ip address 10.0.102.2 255.255.255.252
          - tunnel source 10.0.1.11
          - tunnel destination 10.0.105.2
        parents:
          - interface Tunnel20

    # - name: add loopback11 interface on siteA
    #   ios_config:
    #     provider: "{{cli}}"
    #     lines:
    #       - ip address 10.0.11.10 255.255.255.0
    #     parents:
    #       - interface loopback11

    # - name: add loopback12 interface on siteA
    #   ios_config:
    #     provider: "{{cli}}"
    #     lines:
    #       - ip address 10.0.12.10 255.255.255.0
    #     parents:
    #       - interface loopback12

    - name: Set IPSEC Interesting Traffic Accesslist for vrf site1 on siteA
      ios_config:
        provider: "{{cli}}"
        parents:
          - ip access-list extended 100
        lines:
          - 10 permit ipinip host 10.0.1.11 host 10.0.1.10
          - 20 permit gre host 10.0.1.11 host 10.0.1.10

    - name: Set policy and ISAKMP exchange key on siteA
      ios_config:
        provider: "{{cli}}"
        parents:
          - crypto isakmp policy 10
        lines:
          - hash sha256
          - encryption aes 256
          - group 14
          - authentication pre-share
  
    - name: Define ISAKMP key and Peer on siteA
      ios_config:
        provider: "{{cli}}"
        commands:
          - crypto isakmp key IPsecP@$$ address 10.0.1.10

    - name: Set IPSEC transform-set on siteA
      ios_config:
        provider: "{{cli}}"
        parents:
          - crypto ipsec transform-set TS esp-aes 256 esp-sha-hmac 
        lines:
          - mode tunnel

    - name: Set IPSEC CryptoMap on siteA
      ios_config:
        provider: "{{cli}}"
        parents:
          - crypto map CMAP 10 ipsec-isakmp 
        lines:
          - set peer 10.0.1.10
          - set transform-set TS 
          - match address 100

    - name: add GigabitEthernet2 in vrf site1 subinterface on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site2
          - ip address 10.0.12.10 255.255.255.0
        parents:
          - interface GigabitEthernet2

    - name: add GigabitEthernet3 in vrf site1 subinterface on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - no shutdown
          - vrf forwarding site1
          - ip address 10.0.11.10 255.255.255.0
        parents:
          - interface GigabitEthernet3

    - name: add BGP on siteA for inter-vrf routing for vrf site1, site2
      ios_config:
        provider: "{{cli}}"
        lines:
          - redistribute ospf 10
          - exit-address-family
        parents:
          - router bgp 64000
          - address-family ipv4 vrf site1

    - name: add BGP on siteA for inter-vrf routing for vrf site1, site2
      ios_config:
        provider: "{{cli}}"
        lines:
          - redistribute ospf 20
          - exit-address-family
        parents:
          - router bgp 64000
          - address-family ipv4 vrf site2

    - name: add ospf on siteA for inter-vrf routing for vrf site1
      ios_config:
        provider: "{{cli}}"
        lines:
          - redistribute bgp 64000
        parents:
          - router ospf 10 vrf site1

    - name: add ospf on siteA for inter-vrf routing for vrf site2
      ios_config:
        provider: "{{cli}}"
        lines:
          - redistribute bgp 64000
        parents:
          - router ospf 20 vrf site2

    - name: Set static routes on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - ip route vrf site1 0.0.0.0 0.0.0.0 Tunnel10
          - ip route vrf site2 0.0.0.0 0.0.0.0 Tunnel20
          - ip route 10.0.105.0 255.255.255.248 10.0.1.10

    - name: add crypto-map under GigabitEthernet1 interface on siteA
      ios_config:
        provider: "{{cli}}"
        lines:
          - crypto map CMAP
        parents:
          - interface GigabitEthernet1

